    version: "3.9"
    services:
      web:
        build:
          context: .
          dockerfile: Dockerfile
        command: python3.10 manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/code
        ports:
          - "8000:8000"