# Generated by Django 4.2.7 on 2023-11-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a category for the design request', max_length=200),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='design_request_photos/'),
        ),
    ]
